### ISSUE TITLE
Søgning i plandokumenter

### ISSUE THREAD

**Issue by baffioso** [magloire/vidisearch#1]
Vi skal have indexeret teksten fra plandokumenterne i elasticsearch sammen med de øvrige oplysninger som hentes fra plansystemDK WFS. 

@magloire @Larsklindt @mapcentia Har lavet udkast til python script som opdaterer eksisterende lokalplan-tabel i postgres med tekst fra lokalplandokumenternes pdf'er (gik fint med alle ~150 lokalplaner i Ballerup).

https://gist.github.com/baffioso/79e3c5d32dd11cf677168ab39b72386a

Herefter kan man bruge GC2 til at indexerer i ES. Der skal dog laves lidt tilretninger i scriptet, så det også kan håndtere OCR læsning af de pdf'er der ikke indeholder tekst. Dette kan gøres med [textract](https://textract.readthedocs.io/en/stable/) modulet.

**Comment by mapcentia** [comment]
Det er en god ide at gøre det på den måde. Der skal nok laves en "tracker", som holder styr på hvilke pdf'er, der er ændret, så alle ikke skal downloades og parses hver gang.
